name: CI

on:
  pull_request:
    branches: ['main']
  workflow_call: # This allows the workflow to be called by other workflows

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun lint

      - name: Check formatting
        run: bun format:check
